# TAGS

# all the needed tags here

# browser tags
windowrule = tag +browser, match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$
windowrule = tag +browser, match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$
windowrule = tag +browser, match:class ^(chrome-.+-Default)$ # Chrome PWAs
windowrule = tag +browser, match:class ^([Cc]hromium)$
windowrule = tag +browser, match:class ^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$
windowrule = tag +browser, match:class ^([Bb]rave-browser(-beta|-dev|-unstable)?)$
windowrule = tag +browser, match:class ^([Tt]horium-browser|[Cc]achy-browser)$
windowrule = tag +browser, match:class ^(zen-alpha|zen)$

# terminal
windowrule = tag +terminal, match:class ^(Alacritty|kitty|kitty-dropterm)$

# file manager
windowrule = tag +file-manager, match:class ^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$

# ide
windowrule = tag +ide, match:class ^(codium|codium-url-handler|VSCodium)$
windowrule = tag +ide, match:class ^(VSCode|code-url-handler|code)$
windowrule = tag +ide, match:class ^(jetbrains-.+)$ # JetBrains IDEs

windowrule = tag +multimedia_video, match:class ^([Mm]pv|vlc)$
windowrule = tag +settings, match:class ^(nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller)$
windowrule = tag +settings, match:class ^(org.gnome.DiskUtility|wihotspot(-gui)?)$
windowrule = tag +viewer, match:class ^(org.gnome.SystemMonitor)$ # system monitor
windowrule = tag +viewer, match:class ^(org.gnome.Evince)$ # document viewer 
windowrule = tag +viewer, match:class ^(eog|org.gnome.Loupe)$ # image viewer
