# Symphony
# Author: vyrx
# Theme: Sakura

general {
    col.active_border = rgba(e48b7aee) rgba(f0a19aee) 45deg
    col.inactive_border = rgba(0a122088)
}
# Border colors
$secondary = rgba(e48b7aee) rgba(f0a19aee) 45deg
$outline_variant = rgba(444444ff)

# Shadow configuration
decoration {
    shadow {
        color = rgba(100, 60, 50, 0.4)
        color_inactive = rgba(100, 60, 50, 0.2)
        offset = 2 2
        range = 20
        render_power = 3
    }
}


$outline = $secondary
