
[config]
  mode = "dark"

[templates.kitty]
  input_path  = '~/.config/matugen/templates/terminal/kitty.conf'
  output_path = '~/.config/kitty/themes/Matugen.conf'

[templates.hyprland]
  input_path  = '~/.config/matugen/templates/hypr/hyprland.conf'
  output_path = '~/.config/hypr/hyprland/theme/colors.conf'

[templates.hyprlock-icon]
  input_path  = '~/.config/matugen/templates/hypr/icon.svg'
  output_path = '~/.cache/wal/icon.svg'

[templates.btop]
  input_path  = '~/.config/matugen/templates/terminal/btop.theme'
  output_path = '~/.config/btop/themes/matugen.theme'

[templates.bat]
  input_path  = '~/.config/matugen/templates/terminal/bat.tmTheme'
  output_path = '~/.config/bat/themes/Matugen.tmTheme'

[templates.yazi]
  input_path  = '~/.config/matugen/templates/terminal/yazi.toml'
  output_path = '~/.config/yazi/theme.toml'

[templates.fish]
  input_path  = '~/.config/matugen/templates/terminal/colors.fish'
  output_path = '~/.config/fish/themes/Matugen.theme'

[templates.fzf-fish]
  input_path  = '~/.config/matugen/templates/terminal/fzf.fish'
  output_path = '~/.cache/wal/fzf.fish'

[templates.rofi]
  input_path  = '~/.config/matugen/templates/rofi.rasi'
  output_path = '~/.config/rofi/colors.rasi'

[templates.qtct]
  input_path  = '~/.config/matugen/templates/qtct.conf'
  output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.fzf]
  input_path  = '~/.config/matugen/templates/terminal/fzf.sh'
  output_path = '~/.config/zsh/fzf'

[templates.kvantum]
  input_path  = '~/.config/matugen/templates/kvantum/kvantum.kvconfig'
  output_path = '~/.config/Kvantum/Matugen/Matugen.kvconfig'

[templates.kvantum-svg]
  input_path  = "~/.config/matugen/templates/kvantum/kvantum.svg"
  output_path = "~/.config/Kvantum/Matugen/Matugen.svg"

[templates.gtk4]
  input_path  = '~/.config/matugen/templates/gtk/colors.css'
  output_path = '~/.config/gtk-4.0/colors.css'

[templates.gtk3]
  input_path  = '~/.config/matugen/templates/gtk/colors.css'
  output_path = '~/.config/gtk-3.0/colors.css'

[templates.papirus-folders]
  input_path  = '~/.config/matugen/templates/folder-color.txt'
  output_path = '~/.cache/wal/papirus-folders.txt'

[templates.spicetify]
  input_path  = '~/.config/matugen/templates/spotify.ini'
  output_path = '~/.config/spicetify/Themes/marketplace/color.ini'

[templates.neovim-nvchad]
  input_path  = '~/.config/matugen/templates/nvchad/nvchad.lua'
  output_path = '~/.local/share/nvim/lazy/base46/lua/base46/themes/matugen.lua'

[templates.neovim-nvchad-colors]
  input_path  = '~/.config/matugen/templates/nvchad/colors-nvchad.txt'
  output_path = '~/.cache/wal/colors'

[templates.vesktop]
  input_path  = "~/.config/matugen/templates/discord.css"
  output_path = "~/.config/vesktop/themes/Matugen.css"

[templates.cava]
  input_path  = "~/.config/matugen/templates/terminal/cava.config"
  output_path = "~/.config/cava/config"


[config.custom_colors.red]
  color = "#f38ba8"
  blend = true

[config.custom_colors.green]
  color = "#a6e3a1"
  blend = true

[config.custom_colors.yellow]
  color = "#f9e2af"
  blend = true

[config.custom_colors.blue]
  color = "#89b4fa"
  blend = true

[config.custom_colors.magenta]
  color = "#f5c2e7"
  blend = true

[config.custom_colors.cyan]
  color = "#94e2d5"
  blend = true

[config.custom_colors.orange]
  color = "#fab387"
  blend = true
[config.custom_colors.purple]
  color = "#cba6f7"
  blend = true

[config.custom_keywords]
  font_mono = "JetBrainsMono Nerd Font"
  font_sans = "SF Pro Rounded Semi-Bold"
  font_size = "15"
