fish_color_normal {{colors.on_surface.default.hex_stripped}}
fish_color_command {{colors.primary.default.hex_stripped}}
fish_color_param {{colors.tertiary.default.hex_stripped}}
fish_color_keyword {{colors.tertiary_fixed.default.hex_stripped}}
fish_color_quote {{colors.secondary.default.hex_stripped}}
fish_color_redirection {{colors.tertiary.default.hex_stripped}}
fish_color_end {{colors.secondary.default.hex_stripped}}
fish_color_comment {{colors.outline.default.hex_stripped}}
fish_color_error {{colors.error.default.hex_stripped}}
fish_color_gray {{colors.surface_bright.default.hex_stripped}}
fish_color_selection --background={{colors.inverse_on_surface.default.hex_stripped}}
fish_color_search_match --background={{colors.inverse_on_surface.default.hex_stripped}}
fish_color_option {{colors.surface_tint.default.hex_stripped}}
fish_color_operator {{colors.on_tertiary_container.default.hex_stripped}}
fish_color_escape {{colors.on_tertiary_fixed.default.hex_stripped}}
fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
fish_color_cancel {{colors.error.default.hex_stripped}}
fish_color_cwd {{colors.primary_container.default.hex_stripped}}
fish_color_user {{colors.secondary_container.default.hex_stripped}}
fish_color_host {{colors.tertiary_container.default.hex_stripped}}
fish_color_host_remote {{colors.secondary.default.hex_stripped}}
fish_color_status {{colors.error.default.hex_stripped}}
fish_pager_color_progress {{colors.primary.default.hex_stripped}}
fish_pager_color_prefix {{colors.tertiary.default.hex_stripped}}
fish_pager_color_selected_prefix {{colors.on_tertiary.default.hex_stripped}}
fish_pager_color_completion {{colors.primary.default.hex_stripped}}
fish_pager_color_description {{colors.on_surface_variant.default.hex_stripped}}
fish_pager_color_selected_description {{colors.on_secondary.default.hex_stripped}}
fish_pager_color_selected_background --background={{colors.secondary.default.hex_stripped}}
fish_pager_color_selected_completion {{colors.on_secondary.default.hex_stripped}}
