#!/usr/bin/env bash

# Generated by matugen

export FZF_DEFAULT_OPTS=" \
--height 40% --layout=reverse --border=rounded --info=right \
--pointer='' \
--prompt='❯ ' \
--color=gutter:{{colors.surface.default.hex}} \
--color=bg+:{{colors.surface_container_high.default.hex}} \
--color=bg:{{colors.surface.default.hex}} \
--color=hl:{{colors.primary.default.hex}} \
--color=fg:{{colors.on_surface.default.hex}} \
--color=fg+:{{colors.on_surface.default.hex}} \
--color=header:{{colors.primary.default.hex}} \
--color=info:{{colors.outline.default.hex}} \
--color=marker:{{colors.secondary.default.hex}} \
--color=spinner:{{colors.outline.default.hex}} \
--color=prompt:{{colors.primary.default.hex}} \
--color=pointer:{{colors.primary.default.hex}} \
--color=hl+:{{colors.primary.default.hex}} \
--color=selected-bg:{{colors.surface_container_highest.default.hex}} \
--color=border:{{colors.outline_variant.default.hex}} \
--color=label:{{colors.on_surface_variant.default.hex}} \
"
