[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
opacity = 0.8

[window.padding]
x = 40
y = 40

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "medium"

[window.dimensions]
columns = 80
lines = 120

[general]
live_config_reload = true
# import = ["~/.cache/wal/colors-alacritty.toml"]
import = ["colors.toml"]

